apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-permissionservice
  labels:
    app: {{ .Chart.Name }}-permissionservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-permissionservice
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-permissionservice
    spec:
      containers:
      - name: {{ .Chart.Name }}-permissionservice
        image: "{{ .Values.permissionservice.repository }}:{{ .Values.permissionservice.tag }}"
        ports:
        - containerPort: 7122
          name: http-rest
        - containerPort: 7100
          name: grpc
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:7122"
        - name: ConnectionStrings__DefaultConnection
          value: {{ .Values.env.ConnectionStrings__DefaultConnection }}