apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-redis
  labels:
    app: {{ .Chart.Name }}-redis
spec:
  selector:
    app: {{ .Chart.Name }}-redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.containerPort }}
      targetPort: {{ .Values.redis.containerPort }}
  type: ClusterIP
