apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-roomservice
  labels:
    app: {{ .Chart.Name }}-roomservice
spec:
  selector:
    app: {{ .Chart.Name }}-roomservice-server
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
