# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and Push Images
  jobs:
  - job: BuildImages
    displayName: Build Images
    pool:
      name: Default
      demands:
        - docker
    strategy:
      matrix:
        authservice:
          dockerfile: 'AuthService/Dockerfile'
          serviceName: 'authservice'
        permissionservice:
          dockerfile: 'PermissionService/Dockerfile'
          serviceName: 'permissionservice'
        roomservice:
          dockerfile: 'RoomService/Dockerfile'
          serviceName: 'roomservice'
        userservice:
          dockerfile: 'UserService/Dockerfile'
          serviceName: 'userservice'
    steps:
    - task: Docker@2
      displayName: Build & Push $(Build.Repository.Name) image
      inputs:
        containerRegistry: 'k8sTeamSketch'
        command: buildAndPush
        repository: 'hajduty/$(serviceName)'
        dockerfile: '$(Build.SourcesDirectory)/$(dockerfile)'
        buildContext: '$(Build.SourcesDirectory)'
        tags: '$(tag)'
